src/main/java/managedbeans/administratorBean.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSF/JSFManagedBean.java to edit this template
 */
package managedbeans;

import EJB.freelancerServiceLocal;
import EJB.providerServiceLocal;
import jakarta.inject.Named;
import jakarta.faces.application.FacesMessage;
import jakarta.faces.context.FacesContext;
import jakarta.enterprise.context.SessionScoped;
import jakarta.inject.Inject;
import java.io.Serializable;


/**
 *
 * @author asus
 */

@Named
@SessionScoped
public class administratorBean implements Serializable {

    @Inject
    private freelancerServiceLocal freelancerService;

    private String emailToDelete;
    @Inject
    private providerServiceLocal providerService;

    private String emailToDeleteProvider;

    public String getEmailToDeleteProvider() {
        return emailToDeleteProvider;
    }

    public void setEmailToDeleteProvider(String emailToDeleteProvider) {
        this.emailToDeleteProvider = emailToDeleteProvider;
    }

    public void deleteProvider() {
        try {
            providerService.deleteProviderByEmail(emailToDeleteProvider);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Provider deleted successfully."));
        } catch (Exception e) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Please delete all the jobs of the Provider and try again!"));
        }
    }

    public String getEmailToDelete() {
        return emailToDelete;
    }

    public void setEmailToDelete(String emailToDelete) {
        this.emailToDelete = emailToDelete;
    }

    public void deleteFreelancer() {
        try {
            freelancerService.deleteFreelancerByEmail(emailToDelete);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Freelancer deleted successfully."));
        } catch (Exception e) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Error deleting Freelancer: " + e.getMessage()));
        }
    }
}

src/main/java/managedbeans/freelancerBean.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSF/JSFManagedBean.java to edit this template
 */
package managedbeans;

import EJB.freelancerServiceLocal;
import Entities.freelancer;
import jakarta.ejb.EJB;
import jakarta.inject.Named;
import jakarta.enterprise.context.SessionScoped;
import jakarta.inject.Inject;
import java.io.Serializable;
import Entities.job;
import java.util.List;
import EJB.providerServiceLocal;

/**
 *
 * @author 26625
 */
@Named(value = "freelancerBean")
@SessionScoped
public class freelancerBean implements Serializable{
    
    private String email;
    private String name;
    private String skills;
    private String message;
    private String freelancername;
    private String freelanceremail;
    private String freelancerskills;
    private String freelancermessage;
    private int freelancerid;
    
    private int ID;
    private String Keywords;
    private int selectedJobId;
    
    @EJB
    @Inject
    private freelancerServiceLocal fsl;
    
    @Inject
    private providerServiceLocal psl;

    
    /**
     * Creates a new instance of freelancerBean
     */
    public freelancerBean() {
    }
    
    
    public String showfreelancername(){
        freelancer f1 = fsl.findfreelancerByEmail(email);
        freelancername = f1.getNAME();
        return freelancername;
    }
    
    public String showfreelanceremail(){
        freelancer f2 = fsl.findfreelancerByEmail(email);
        freelanceremail = f2.getEMAIL();
        return freelanceremail;
    }

    public int showfreelancerid(){
        freelancer f3 = fsl.findfreelancerByEmail(email);
        freelancerid = f3.getFREELANCERID();
        return freelancerid;
    }
    
    public String showfreelancerskills(){
        freelancer f4 = fsl.findfreelancerByEmail(email);
        freelancerskills = f4.getSKILLS();
        return freelancerskills;
    }
    
    public String showfreelancermessage(){
        freelancer f5 = fsl.findfreelancerByEmail(email);
        freelancermessage = f5.getMESSAGE();
        return freelancermessage;
    }
    
    public void updateFreelancerInfo(){
        freelancer f = fsl.findfreelancerByEmail(email);
        if (f != null){
            f.setMESSAGE(message);
            f.setSKILLS(skills);
            if (!"".equals(name)){
                f.setNAME(name);
            }
            fsl.updateFreelancer(f);
        }
    }  
    
    public List<job> showalljobs(){
        List<job> j = fsl.freelancershowalljobs();
        return j;
    }
    
    public List<job> searchbyid(){
        List<job> j = fsl.searchbyid(ID);
        return j;
    }

    public List<job> searchbykeywords(){
        List<job> j = fsl.searchbykeywords(Keywords);
        return j;
    }
    
    
    public void saveSelectedJobId(int jobId) {
        setSelectedJobId(jobId);
    }
    
    public double getFreelancerPaymentAccount() {
    freelancer f = fsl.findfreelancerByEmail(email);
    return f.getPAYMENT_ACCOUNT();
}
    
    public void applyjob() {
        freelancer f = fsl.findfreelancerByEmail(email);
        fsl.freelancerapplyjobs(selectedJobId,f.getFREELANCERID());
    }
    
    public List<job> applications(){
        List<job> j = fsl.freelancerallapplications(email);
        return j;
    }
    
    public void revokeapp(){
        freelancer f = fsl.findfreelancerByEmail(email);
        fsl.deleteApplication(f.getFREELANCERID(), selectedJobId);
    }
    
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSkills() {
        return skills;
    }

    public void setSkills(String skills) {
        this.skills = skills;
    }

    public String getMessage() {
        return message;
    }

    public String getFreelancername() {
        return freelancername;
    }

    public void setFreelancername(String freelancername) {
        this.freelancername = freelancername;
    }

    public String getFreelanceremail() {
        return freelanceremail;
    }

    public void setFreelanceremail(String freelanceremail) {
        this.freelanceremail = freelanceremail;
    }

    public String getFreelancerskills() {
        return freelancerskills;
    }

    public void setFreelancerskills(String freelancerskills) {
        this.freelancerskills = freelancerskills;
    }

    public String getFreelancermessage() {
        return freelancermessage;
    }

    public void setFreelancermessage(String freelancermessage) {
        this.freelancermessage = freelancermessage;
    }

    public int getFreelancerid() {
        return freelancerid;
    }

    public void setFreelancerid(int freelancerid) {
        this.freelancerid = freelancerid;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public String getKeywords() {
        return Keywords;
    }

    public void setKeywords(String Keywords) {
        this.Keywords = Keywords;
    }

    public freelancerServiceLocal getFsl() {
        return fsl;
    }

    public void setFsl(freelancerServiceLocal fsl) {
        this.fsl = fsl;
    }

    
    public void setMessage(String message) {
        this.message = message;
    }

    public int getSelectedJobId() {
        return selectedJobId;
    }

    public void setSelectedJobId(int selectedJobId) {
        this.selectedJobId = selectedJobId;
    }






    
    
}

src/main/java/managedbeans/login_signupBean.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSF/JSFManagedBean.java to edit this template
 */
package managedbeans;

import jakarta.ejb.EJB;
import jakarta.inject.Named;
import EJB.login_signupServiceLocal;
import jakarta.faces.application.FacesMessage;
import jakarta.faces.context.FacesContext;
import jakarta.validation.ConstraintViolationException;
import jakarta.enterprise.context.SessionScoped;
import jakarta.inject.Inject;
import java.io.Serializable;


/**
 *
 * @author asus
 */
@Named(value = "login_signupBean")
@SessionScoped
public class login_signupBean implements Serializable {
    
    private String name;
    private String email;
    private String password;
    private String loginEmail;
    private String loginPassword;
    @Inject
    private freelancerBean freelancerBean;
    @Inject
    private providerBean providerBean;
    


    @EJB
    private login_signupServiceLocal lsl;

public String freelancersignup() {
    try {
        lsl.freelancer_signup(name, email, password);
        return "registrationSuccess";
    } catch (ConstraintViolationException e) {
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Validation Error", e.getMessage()));
        return "";
    }
}

public String providersignup() {
    try {
        lsl.provider_signup(name, email, password);
        return "registrationSuccess";
    } catch (ConstraintViolationException e) {
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Validation Error", e.getMessage()));
        return "";
    }
}

public String administratorsignup() {
    try {
        lsl.administrator_signup(name, email, password);
        return "registrationSuccess";
    } catch (ConstraintViolationException e) {
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Validation Error", e.getMessage()));
        return "";
    }
}


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    public login_signupBean(){
    
    }
    
    public String getLoginEmail() {
        return loginEmail;
    }

    public void setLoginEmail(String loginEmail) {
        this.loginEmail = loginEmail;
    }

    public String getLoginPassword() {
        return loginPassword;
    }

    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }
    
    // Add the login method
    public String freelancerLogin() {
        if (lsl.validateFreelancer(loginEmail, loginPassword)) {
            freelancerBean.setEmail(loginEmail);
            return "freelancerMain";
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Invalid email or password", null));
            return null; // 保持在当前页面
        }
    }
    
    public String providerLogin() {
        if (lsl.validateProvider(loginEmail, loginPassword)) {
            providerBean.setEMAIL(loginEmail);
            return "providerMain";
        } else {
            FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, "Invalid email or password", null);
            FacesContext.getCurrentInstance().addMessage(null, message);
            return null;
        }
    }

    public String administratorLogin() {
        if (lsl.validateAdministrator(loginEmail, loginPassword)) {
            return "administratorMain";
        } else {
            FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, "Invalid email or password", null);
            FacesContext.getCurrentInstance().addMessage(null, message);
            return null;
        }
    }

 
}

src/main/java/managedbeans/providerBean.java
package managedbeans;

import EJB.providerServiceLocal;
import Entities.job;
import Entities.jobapplication;
import Entities.provider;
import jakarta.inject.Named;
import jakarta.enterprise.context.SessionScoped;
import jakarta.inject.Inject;
import java.io.Serializable;
import java.util.List;

@Named(value = "providerBean")
@SessionScoped
public class providerBean implements Serializable {

    private int PROVIDERID;
    private String NAME;
    private String EMAIL;
    private String PASSWORD;

    private String TITLE;
    private String DESCRIPTION;
    private String STATUS;
    private String KEYWORDS;
    private Double PAYMENT_OFFER;
    private int selectedFreelancerId;
    private int selectedJobId;
    
    List<jobapplication> ja;

    // New property
    private List<job> jobs;

    @Inject
    private providerServiceLocal psl;

    // Getters and Setters
    public int getPROVIDERID() {
        return PROVIDERID;
    }

    public void setPROVIDERID(int PROVIDERID) {
        this.PROVIDERID = PROVIDERID;
    }

    public String getNAME() {
        return NAME;
    }

    public void setNAME(String NAME) {
        this.NAME = NAME;
    }

    public String getEMAIL() {
        return EMAIL;
    }

    public void setEMAIL(String EMAIL) {
        this.EMAIL = EMAIL;
    }

    public String getSTATUS() {
        return STATUS;
    }

    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS;
    }

    public String getKEYWORDS() {
        return KEYWORDS;
    }

    public void setKEYWORDS(String KEYWORDS) {
        this.KEYWORDS = KEYWORDS;
    }

    public Double getPAYMENT_OFFER() {
        return PAYMENT_OFFER;
    }

    public void setPAYMENT_OFFER(Double PAYMENT_OFFER) {
        this.PAYMENT_OFFER = PAYMENT_OFFER;
    }

    public providerServiceLocal getPsl() {
        return psl;
    }

    public void setPsl(providerServiceLocal psl) {
        this.psl = psl;
    }

    public String getPASSWORD() {
        return PASSWORD;
    }

    public void setPASSWORD(String PASSWORD) {
        this.PASSWORD = PASSWORD;
    }

    public String getTITLE() {
        return TITLE;
    }

    public void setTITLE(String TITLE) {
        this.TITLE = TITLE;
    }

    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION;
    }

    public int getSelectedFreelancerId() {
        return selectedFreelancerId;
    }

    public void setSelectedFreelancerId(int selectedFreelancerId) {
        this.selectedFreelancerId = selectedFreelancerId;
    }

    public int getSelectedJobId() {
        return selectedJobId;
    }

    public void setSelectedJobId(int selectedJobId) {
        this.selectedJobId = selectedJobId;
    }
    
    
//public List<jobapplication> showapplications() {
//    provider p = psl.findproviderByEmail(EMAIL);
//    ja = psl.getJobApplicationsWithMessages(p.getPROVIDERID());
//    return ja;
//}

// ...



    
    // New methods
    public List<job> getJobs() {
        return jobs;
    }

    public void setJobs(List<job> jobs) {
        this.jobs = jobs;
    }

    public void fetchJobs() {
        jobs = psl.getJobsByProvider(EMAIL);
    }

    public void publicJob() {
        psl.createJob(TITLE, DESCRIPTION, EMAIL, "open", KEYWORDS, PAYMENT_OFFER);
    }
    
    public void revokeJob(int jobId) {
        psl.revokeJob(jobId);
        fetchJobs(); // 重新获取当前用户的工作列表
    }
    
    public void saveSelectedFreelancerId(int freelancerId) {
        setSelectedFreelancerId(freelancerId);
    }
    
    public void saveSelectedJobId(int jobId) {
        setSelectedJobId(jobId);
    }
    


    
    public void acceptapp(){
        psl.acceptapplications(selectedFreelancerId, selectedJobId);
    }
    
    public void completedapp(){
        psl.completeapplications(selectedJobId,PAYMENT_OFFER,selectedFreelancerId);
    }
    
    
    
}

src/main/webapp/account.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
<head>
    <title>Account</title>
</head>
<body>
    <h:form>
        <h:outputText value="Payment Account: #{freelancerBean.freelancerPaymentAccount}" /><br/>
    </h:form>
</body>
</html>

src/main/webapp/adminDelFreelancer.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet name="css/csslayout.css"/>
        <title>Delete Freelancer</title>
    </h:head>
    <h:body>
        <h:form>
            <h:outputLabel for="emailToDelete" value="Email to delete:" />
            <br/>
            <h:inputText id="emailToDelete" value="#{administratorBean.emailToDelete}" />
            <br/>
            <h:commandButton value="Delete Freelancer" action="#{administratorBean.deleteFreelancer}" />
        </h:form>

        <br/>
        <button onclick="location.href = 'administratorMain.xhtml'">Back</button>
    </h:body>
</html>

src/main/webapp/administratorMain.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <h:outputStylesheet name="css/csslayout.css"/>
            <title>Administrator Main</title>
    </h:head>
    
    <h:body>
        
        <dev class="sidebar"> 
            <button class="link-button" onclick="location.href='freelancerRegister.xhtml'">Add Freelaner</button>
            <button class="link-button" onclick="location.href='adminDelFreelancer.xhtml'">Del Freelaner</button>
            <button class="link-button" onclick="location.href='providerRegister.xhtml'">Add Provider</button>
            <button class="link-button" onclick="location.href='adminDelProvider.xhtml'">Del Provider</button>
            <button class="link-button" onclick="location.href='index.xhtml'">Logout</button>
        </dev>
        
    </h:body>
</html>

src/main/webapp/administratorRegister.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet name="css/csslayout.css"/>
        <title>Administrator  Register</title>
    </h:head>
    <h:body >
            <div class="main">
                <h1>Administrator  Register</h1>
                <h:form>
                    Please enter your Name:<h:inputText value="#{login_signupBean.name}" styleClass="link-button"/><br/>
                    Please enter your Email:<h:inputText value="#{login_signupBean.email}" styleClass="link-button"/><br/>
                    Please enter your Password:<h:inputText value="#{login_signupBean.password}" styleClass="link-button"/><br/>
                    <h:commandButton value="submit" action="#{login_signupBean.administratorsignup()}" styleClass="link-button"/>
                    <h:commandButton value="back" action="index" styleClass="link-button"/>
                </h:form>
            </div>
    </h:body>
</html>

src/main/webapp/freelancerApplication.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:dataTable value="#{freelancerBean.applications()}" var="job">
    <h:column>
        <f:facet name="header">JOBID</f:facet>
        #{job.JOBID} 
    </h:column>
    <h:column>
        <f:facet name="header">TITLE</f:facet>
        #{job.APPLICATIONID}
    </h:column>
    <h:column>
        <f:facet name="header">STATUS</f:facet>
        #{job.STATUS}
    </h:column>
            <h:column>
                <f:facet name="header">Action</f:facet>
                <h:form>
                <h:commandButton value="REVOKE" action="#{freelancerBean.revokeapp()}"  >
                <f:setPropertyActionListener target="#{freelancerBean.selectedJobId}" value="#{job.JOBID}" />
                </h:commandButton>
                </h:form>
            </h:column>
</h:dataTable>
    </h:body>
</html>

src/main/webapp/freelancerFindjob.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>Job List</title>
</h:head>
<h:body>
    <h:form>
        <h:outputLabel value="Search by Job ID: " for="searchById" />
        <h:inputText id="searchById" value="#{freelancerBean.ID}" />
        <h:commandButton value="Search" action="freelancerjobid" />
        <br />
        <h:outputLabel value="Search by Keywords: " for="searchByKeywords" />
        <h:inputText id="searchByKeywords" value="#{freelancerBean.keywords}" />
        <h:commandButton value="Search" action="freelancerjobkeywords" />
    </h:form>
    <h:dataTable value="#{freelancerBean.showalljobs()}" var="job">
    <h:column>
        <f:facet name="header">JOBID</f:facet>
        #{job.JOBID} 
    </h:column>
    <h:column>
        <f:facet name="header">TITLE</f:facet>
        #{job.TITLE}
    </h:column>
    <h:column>
        <f:facet name="header">KEYWORDS</f:facet>
        #{job.KEYWORDS}
    </h:column>
    <h:column>
        <f:facet name="header">DESCRIPTION</f:facet>
        #{job.DESCRIPTION}
    </h:column>
    <h:column>
        <f:facet name="header">PAYMENT_OFFER</f:facet>
        #{job.PAYMENT_OFFER}
    </h:column>
    <h:column>
        <f:facet name="header">STATUS</f:facet>
        #{job.STATUS}
    </h:column>
    <h:column>
        <f:facet name="header">PROVIDERID</f:facet>
        #{job.PROVIDERID}
    </h:column>
    <h:column>
                <f:facet name="header">Action</f:facet>
                <h:form>
                <h:commandButton value="APPLY" action="#{freelancerBean.applyjob()}"  >
                <f:setPropertyActionListener target="#{freelancerBean.selectedJobId}" value="#{job.JOBID}" />
                </h:commandButton>
                </h:form>
            </h:column>
</h:dataTable>
</h:body>
</html>

src/main/webapp/freelancerLogin.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <h:outputStylesheet name="css/csslayout.css"/>
            <title>Freelancer Login</title>
    </h:head>
    <h:body>
        <div class="main">
            <h2>Freelancer Login</h2>
            <h:form>
                <h:outputLabel value="Email: " for="email" />
                <h:inputText id="email" value="#{login_signupBean.loginEmail}" required="true" />
                <br />
                <h:outputLabel value="Password: " for="password" />
                <h:inputSecret id="password" value="#{login_signupBean.loginPassword}" required="true" />
                <br />
                <h:commandButton value="Login" action="#{login_signupBean.freelancerLogin}" />
                <h:commandButton value="back" action="index" immediate="true"/>
            </h:form>
        </div>
    </h:body>
</html>

src/main/webapp/freelancerMain.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <h:outputStylesheet name="css/csslayout.css"/>
            <title>Freelancer Profiles</title>
    </h:head>

    <h:body>
        <div class="sidebar">
            <button class="link-button" onclick="location.href='freelancerMain.xhtml'">Profile</button>
            <button class="link-button" onclick="location.href='freelancerFindjob.xhtml'">Finding Job</button>
            <button class="link-button" onclick="location.href='freelancerApplication.xhtml'">My Application</button>
            <button class="link-button" onclick="location.href='account.xhtml'">Account</button>
            <button class="link-button" onclick="location.href='index.xhtml'">Logout</button>
        </div>

        <div class="top">
            <h1>Profile</h1>
        </div>
        
        <div class="bottom-right">
            <ui:insert name="bottom-right">
                <ui:include src="/template/Signatures.xhtml"/>
            </ui:insert>
        </div>
       

        <div class="content">
            <h:form>
                <h:outputLabel for="ID" value="ID:" styleClass="inf-table"/>
                <h:outputText id="ID" value="#{freelancerBean.showfreelancerid()}"/>
                <br/>
                <h:outputLabel for="name" value="name:" styleClass="inf-table"/>
                <h:inputText id="name" value="#{freelancerBean.name}" p:placeholder="#{freelancerBean.showfreelancername()}"/>
                <br/>
                <h:outputLabel for="e-mail" value="e-mail:" styleClass="inf-table"/>
                <h:outputText id="e-mail" value="#{freelancerBean.showfreelanceremail()}" />
                <br/>
                <h:outputLabel for="skills" value="list of skills:" styleClass="inf-table"/>
                <h:inputText id="skills" value="#{freelancerBean.skills}" p:placeholder="#{freelancerBean.showfreelancerskills()}"/>
                <br/>
                <h:outputLabel for="message" value="message:" styleClass="inf-table"/>
                <h:inputTextarea id="message" value="#{freelancerBean.message}" p:placeholder="#{freelancerBean.showfreelancermessage()}"/>
                <br/>
                <h:commandButton value="SAVE" action="#{freelancerBean.updateFreelancerInfo()}" styleClass="link-button" style="display: block; margin: 0 auto;"/>
            </h:form>
        </div>
    </h:body>
</html>

src/main/webapp/freelancerRegister.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <h:outputStylesheet name="css/csslayout.css"/>
            <title>Freelancer Register</title>
    </h:head>
    <h:body>
        <div class="main">
            <h1>Freelancer Register</h1>
            <h:form>
                Please enter your name: <h:inputText value="#{login_signupBean.name}"/><br/>
                Please enter your Email:<h:inputText value="#{login_signupBean.email}"/><br/>
                Please enter your Password:<h:inputText value="#{login_signupBean.password}"/><br/>
                <h:commandButton value="submit" action="#{login_signupBean.freelancersignup()}"/>
                <h:commandButton value="back" onclick="window.history.back(); return false;" styleClass="link-button"/>
            </h:form>
        </div>
    </h:body>
</html>

src/main/webapp/providerRegister.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <h:outputStylesheet name="css/csslayout.css"/>
            <title>Provider Register</title>
    </h:head>
    <h:body>
        <div class="main">
            <h1>Provider Register</h1>
            <h:form>
                Please enter your name: <h:inputText value="#{login_signupBean.name}"/><br/>
                Please enter your Email:<h:inputText value="#{login_signupBean.email}"/><br/>
                Please enter your Password:<h:inputText value="#{login_signupBean.password}"/><br/>
                <h:commandButton value="submit" action="#{login_signupBean.providersignup()}"/>
                <h:commandButton value="back" onclick="window.history.back(); return false;" styleClass="link-button"/>
            </h:form>
        </div>
    </h:body>
</html>